import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#121212",
    },
    scroll: {
        flexGrow: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 24,
        paddingTop: 56, // mais espaço para o botão de voltar absoluto
    },
    backButton: {
        position: "absolute",
        top: 56,
        left: 24,
        paddingVertical: 6,
        paddingHorizontal: 12,
        zIndex: 10,
        backgroundColor: "#1e1e1e",
        borderRadius: 9999,
        shadowColor: "#000",
        shadowOpacity: 0.25,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
    },
    backButtonText: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "600",
        opacity: 0.8,
    },
    title: {
        fontSize: 34,
        color: "#ffffff",
        fontWeight: "800",
        marginBottom: 12,
        textAlign: "center",
    },
    subtitle: {
        fontSize: 16,
        color: "#b0b0b0",
        textAlign: "center",
        lineHeight: 22,
        marginBottom: 32,
        paddingHorizontal: 12,
    },
    input: {
        width: "100%",
        backgroundColor: "#1e1e1e",
        color: "#ffffff",
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        fontSize: 16,
        borderWidth: 1,
        borderColor: "#333333",
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
    },
    inputFocused: {
        borderColor: "#ffffff",
        shadowOpacity: 0.4,
        shadowRadius: 6,
    },
    // container para input de senha + olho
    passwordContainer: {
        width: "100%",
        position: "relative",
        marginBottom: 16,
    },
    inputPassword: {
        width: "100%",
        backgroundColor: "#1e1e1e",
        color: "#fff",
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 16,
        fontSize: 16,
        borderWidth: 1,
        borderColor: "#333",
    },
    eyeButton: {
        position: "absolute",
        right: 16,
        top: "50%",
        transform: [{ translateY: -12 }],
        opacity: 0.4,
    },
    button: {
        width: "100%",
        backgroundColor: "#ffffff",
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: "center",
        marginTop: 16,
        shadowColor: "#000",
        shadowOpacity: 0.25,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
    },
    buttonText: {
        color: "#121212",
        fontSize: 16,
        fontWeight: "700",
    },
    dividerContainer: {
        flexDirection: "row",
        alignItems: "center",
        width: "100%",
        marginVertical: 24,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: "#333333",
    },
    dividerText: {
        marginHorizontal: 12,
        fontSize: 14,
        color: "#b0b0b0",
        fontWeight: "500",
    },
    linkText: {
        color: "#b0b0b0",
        fontSize: 14,
        marginTop: 16,
        textAlign: "center",
    },
    linkHighlight: {
        color: "#ffffff",
        fontWeight: "700",
    },
});
