import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: "#121212", 
    },
    keyboardAvoiding: {
        flex: 1,
    },
    container: {
        flexGrow: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingHorizontal: 24,
        backgroundColor: "#121212",
    },
    header: {
        alignItems: "center",
        marginBottom: 40,
    },
    title: {
        fontSize: 32,
        fontWeight: "800",
        color: "#ffffff",
    },
    subtitle: {
        fontSize: 16,
        color: "#b0b0b0",
        marginTop: 8,
        textAlign: "center",
        lineHeight: 22,
    },
    form: {
        width: "100%",
    },
    inputGroup: {
        marginBottom: 20,
    },
    label: {
        fontSize: 14,
        fontWeight: "500",
        color: "#e5e5e5",
        marginBottom: 8,
    },
    input: {
        backgroundColor: "#1e1e1e",
        borderWidth: 1,
        borderColor: "#333333",
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: "#ffffff",
        width: "100%",
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
    },
    inputError: {
        borderColor: "#ff4d4f",
    },
    fieldError: {
        color: "#ff4d4f",
        fontSize: 12,
        marginTop: 6,
    },
    labelContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
        marginBottom: 8,
    },
    forgotPassword: {
        fontSize: 14,
        fontWeight: "500",
        color: "#b0b0b0",
        textAlign: "right",
        marginTop: 5,
    },
    passwordInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#1e1e1e",
        borderWidth: 1,
        borderColor: "#333333",
        borderRadius: 10,
    },
    eyeIcon: {
        position: "absolute",
        right: 12,
    },
    loginError: {
        color: "#ff4d4f",
        fontSize: 14,
        marginTop: 10,
        textAlign: "center",
    },
    signInButton: {
        backgroundColor: "#ffffff",
        paddingVertical: 16,
        borderRadius: 10,
        width: "100%",
        alignItems: "center",
        marginTop: 10,
        shadowColor: "#000",
        shadowOpacity: 0.25,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
    },
    signInButtonDisabled: {
        backgroundColor: "#555555",
    },
    signInButtonText: {
        color: "#121212",
        fontSize: 16,
        fontWeight: "700",
    },
    dividerContainer: {
        flexDirection: "row",
        alignItems: "center",
        width: "100%",
        marginVertical: 30,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: "#333333",
    },
    dividerText: {
        marginHorizontal: 16,
        fontSize: 14,
        color: "#b0b0b0",
        fontWeight: "500",
    },
    socialLoginContainer: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        width: "100%",
        gap: 20,
    },
    socialButton: {
        padding: 12,
        borderWidth: 1,
        borderColor: "#333333",
        borderRadius: 9999,
        backgroundColor: "#1e1e1e",
    },
    signUpText: {
        marginTop: 40,
        fontSize: 14,
        color: "#b0b0b0",
        textAlign: "center",
    },
    signUpLink: {
        color: "#ffffff",
        fontWeight: "700",
    },
});
